services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: flowparser_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://admin:admin@db:5432/flowparser_db
      - SECRET_KEY=dev-secret-change-me
      - ACCESS_TOKEN_EXPIRE_MINUTES=43200
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    depends_on:
      - api
    environment:
      - INTERNAL_API_BASE_URL=http://api:8000        # dla kodu serwerowego Next
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000  # dla przeglądarki
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["sh", "-c", "npm install && npm run dev"]


volumes:
  pgdata:
